// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd53auuMAgNJUyqkfb8-ipKQS5TnBech4',
    appId: '1:574431992249:web:7623662a4abc3779e73e68',
    messagingSenderId: '574431992249',
    projectId: 'portoprofile',
    authDomain: 'portoprofile.firebaseapp.com',
    databaseURL: 'https://portoprofile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portoprofile.appspot.com',
    measurementId: 'G-4CWTQ277N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwbDFQhC0JVsOgkb9prwUiqaUKMhncWqw',
    appId: '1:574431992249:android:f47de7c97a54637ee73e68',
    messagingSenderId: '574431992249',
    projectId: 'portoprofile',
    databaseURL: 'https://portoprofile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portoprofile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJY-9aYZBRFUJGsG0Cfdhx3VY0Z2zhNQ0',
    appId: '1:574431992249:ios:32b225e4d1bdad6ae73e68',
    messagingSenderId: '574431992249',
    projectId: 'portoprofile',
    databaseURL: 'https://portoprofile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portoprofile.appspot.com',
    iosBundleId: 'com.example.protoprofile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJY-9aYZBRFUJGsG0Cfdhx3VY0Z2zhNQ0',
    appId: '1:574431992249:ios:45f366f49452e711e73e68',
    messagingSenderId: '574431992249',
    projectId: 'portoprofile',
    databaseURL: 'https://portoprofile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'portoprofile.appspot.com',
    iosBundleId: 'com.example.protoprofile.RunnerTests',
  );
}
